@echo off
echo Saving training files...
poetry run rasa data validate

echo Running Rasa API in debug mode...
start cmd /k "poetry run rasa run --enable-api --debug"

echo Running Rasa actions server...
start cmd /k "poetry run rasa run actions"

echo Training Rasa model...
poetry run rasa train

echo Running Rasa shell on port 5007...
start cmd /k "poetry run rasa shell --port 5007"
